window.ARCHIVE_ALBUMS = Object.freeze([
  {
    id: 'glass-shoes',
    year: 2017,
    type: 'single',
    title: 'Glass Shoes',
    displayTitle: 'Glass Shoes',
    releaseDate: '2017-11-30',
    titleTrack: '유리구두 (Glass Shoes)',
    tracks: ['유리구두 (Glass Shoes)'],
    description: '프로미스나인의 데뷔 선행 싱글. 동화적인 설렘을 담은 첫 활동의 시작점이다.',
    officialVideoUrl: '',
    sources: ['https://www.genie.co.kr/detail/albumInfo?axnm=81007928', 'https://m.ytn.co.kr/news_view.amp.php?param=1408_201711301800029938']
  },
  {
    id: 'to-heart',
    year: 2018,
    type: 'mini',
    title: 'To. Heart',
    displayTitle: 'To Heart',
    releaseDate: '2018-01-24',
    titleTrack: 'To Heart',
    tracks: ['나에게로 오는 길 (Intro.)', 'To Heart', '환상속의 그대', '피노키오', 'Be With You', '유리구두 (MAMA Ver.)'],
    description: '프로미스나인의 첫 미니 앨범. 수줍지만 먼저 다가가고 싶은 마음을 밝은 팝 댄스로 풀어냈다.',
    officialVideoUrl: '',
    sources: ['https://www.etnews.com/20180124000460', 'https://www.hankyung.com/article/2018012634571']
  },
  {
    id: '9-way-ticket',
    year: 2021,
    type: 'single',
    title: '9 WAY TICKET',
    displayTitle: 'WE GO',
    releaseDate: '2021-05-17',
    titleTrack: 'WE GO',
    tracks: ['Airplane Mode', 'WE GO', 'Promise'],
    description: '어디든 떠나고 싶은 마음을 산뜻한 에너지로 그린 두 번째 싱글 앨범이다.',
    officialVideoUrl: '',
    sources: ['https://www.pledis.co.kr/ko/artist/detail/fromisnine/discography/pledis.co.kr']
  },
  {
    id: 'midnight-guest',
    year: 2022,
    type: 'mini',
    title: 'Midnight Guest',
    displayTitle: 'DM',
    releaseDate: '2022-01-17',
    titleTrack: 'DM',
    tracks: ['Escape Room', 'DM', 'Love is Around', 'Hush Hush', '0g'],
    description: '도시의 밤을 자유롭게 누비는 감정과 과감한 고백을 담은 네 번째 미니 앨범이다.',
    officialVideoUrl: '',
    sources: ['https://www.genie.co.kr/detail/albumInfo?axnm=82481993', 'https://www.yes24.com/product/goods/106230912']
  },
  {
    id: 'unlock-my-world',
    year: 2023,
    type: 'album',
    title: 'Unlock My World',
    displayTitle: '#menow',
    releaseDate: '2023-06-05',
    titleTrack: '#menow',
    tracks: ['Attitude', '#menow', 'Wishlist', 'In the Mirror', "Don't Care", 'Prom Night', 'Bring It On', 'What I Want', 'My Night Routine', '눈맞춤 (Eye Contact)'],
    description: '프로미스나인의 첫 정규 앨범. 지금의 자신을 솔직하게 마주하고 새로운 세계를 열어가는 이야기를 담았다.',
    officialVideoUrl: '',
    sources: ['https://www.pledis.co.kr/artist/detail/fromisnine/notice/11557/', 'https://www.yes24.com/product/goods/119136049']
  },
  {
    id: 'supersonic',
    year: 2024,
    type: 'single',
    title: 'Supersonic',
    displayTitle: 'Supersonic',
    releaseDate: '2024-08-12',
    titleTrack: 'Supersonic',
    tracks: ['Supersonic', 'Beat the Heat', 'Take A Chance'],
    description: '무더운 여름을 시원하게 가르는 에너지와 자신감을 담은 세 번째 싱글 앨범이다.',
    officialVideoUrl: '',
    sources: ['https://www.pledis.co.kr/artist/detail/fromisnine/notice/14247/', 'https://www.pledis.co.kr/ko/artist/detail/fromisnine/discography/pledis.co.kr']
  },
  {
    id: 'from-our-20s',
    year: 2025,
    type: 'mini',
    title: "From Our 20's",
    displayTitle: 'LIKE YOU BETTER',
    releaseDate: '2025-06-25',
    titleTrack: 'LIKE YOU BETTER',
    tracks: ['LIKE YOU BETTER', 'REBELUTIONAL', 'Love=Disaster', 'Strawberry Mimosa', 'Twisted love', 'Merry Go Round'],
    description: '아름다운 20대를 살아가는 프로미스나인의 감정과 순간을 진솔하게 담은 여섯 번째 미니 앨범이다.',
    officialVideoUrl: 'https://www.youtube.com/watch?v=r1QapH1SIAI',
    sources: ['https://v.daum.net/v/Wr9y2DIiTy?f=p', 'https://v.daum.net/v/bDfgWhGkOo']
  },
  {
    id: 'glow-me',
    year: 2026,
    type: 'album',
    title: 'Glow ME',
    displayTitle: 'Glow ME',
    releaseDate: '2026-07-21',
    titleTrack: 'Vitamin ME',
    tracks: ['ETERNAL', 'Vitamin ME', 'Pocket Treat', 'Blue Heart', 'Screen Time', 'Teacher', 'Cold Blood (CHAEYOUNG X NAGYUNG X JIHEON)', 'Why do I cry? (HAYOUNG X JIWON)', 'Day 1', 'Wonderland'],
    description: '프로미스나인의 두 번째 정규 앨범. 타이틀곡 ‘Vitamin ME’를 포함한 열 곡으로 한여름의 선명한 에너지와 다섯 멤버의 새로운 색을 담았다.',
    officialVideoUrl: 'https://www.youtube.com/watch?v=sLk8zWUuYTA',
    sources: ['https://music.youtube.com/playlist?list=OLAK5uy_mhn9rcJzA-k_4eUJ-vW64Th1JWLFJSfbo', 'https://www.youtube.com/watch?v=sLk8zWUuYTA']
  }
]);
